name: Release

env:
  PKG_REPO: "https://kl.netlib.re/forge/selfhoster1312/torrentdiag"
  PKG_REF: "9c89a4479a66669f18a35aca702434fab126a7bc"
  PKG_VERSION: "2026.07.09-1"

  # Preview mode: Publishes the build output as a CI artifact instead of creating
  # a release, allowing for manual inspection of the output. This mode is
  # activated if the CI run was triggered by events other than pushed tags, or
  # if the repository is a fork.
  preview: ${{ !startsWith(github.ref, 'refs/tags/') || github.repository != 'ci-prebuild/torrentdiag' }}

on:
  push:
    tags:
    - '[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+'
    branches:
    - 'patch/ci-release-*'
    - 'main'
  pull_request:
    paths:
    - '.github/workflows/release.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  build:
    name: Build ${{ matrix.build }}
    env:
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # don't fail other jobs if one fails
      matrix:
        build: [amd64, arm64]
        include:
        - build: amd64
          # WARN: When changing this to a newer version, make sure that the GLIBC isnt too new, as this can cause issues
          # with portablity on older systems that dont follow ubuntus more rapid release cadence.
          os: ubuntu-22.04
          rust: stable
        - build: arm64
          # Version should be kept in lockstep with the x86_64 version
          os: ubuntu-22.04-arm
          rust: stable

    steps:
      - name: Checkout sources
        run: |
          git clone ${{ env.PKG_REPO }} .
          git checkout ${{ env.PKG_REF }}

      - name: Install ${{ matrix.rust }} toolchain
        uses: dtolnay/rust-toolchain@fa04a1451ff1842e2626ccb99004d0195b455a88 # master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Prepare paths
        run: |
          cat <<EOF >>$GITHUB_ENV
          PKG_DEB=target/debian/torrentdiag_${{ env.PKG_VERSION }}_${{ matrix.build }}.deb
          PKG_TARBALL=torrentdiag_${{ env.PKG_VERSION }}_${{ matrix.build }}.tar.xz
          EOF

      - name: Show command used for Cargo
        run: |
          echo "target flag is: ${{ env.TARGET_FLAGS }}"

      - name: Build release binary
        run: cargo build --release --no-default-features --features embed --locked

      - name: Prepare dist for ${{ env.PKG_TARBALL }}
        shell: bash
        run: |
          mkdir -p dist
          cp "target/release/torrentdiag" "dist/"
          tar cJf ${{ env.PKG_TARBALL }} dist/*

      - name: Upload ${{ env.PKG_TARBALL }} to artifacts
        uses: actions/upload-artifact@v7
        if: env.preview == 'true'
        with:
          path: ${{ env.PKG_TARBALL }}
          archive: false
          if-no-files-found: error

      - name: Upload helix-${{ matrix.build }}.tar.xz to release
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # 2.11.5
        if: env.preview == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.PKG_TARBALL }}
          tag: ${{ github.ref_name }}
          overwrite: true
